name: qkeras-hls4ml-iccad
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pydot
  - graphviz
  - pip
  - pip:
    - jupyter
    - tensorflow==2.3.1
    - git+git://github.com/thesps/hls4ml.git@qk_dev#egg=qk_dev[profiling] 
    - git+git://github.com/google/qkeras.git#egg=qkeras
